import os
import dicomLib
import shutil


def deleteAutoGeneratedFile(lst: list()):
    '''
    delete auto generated file .DS_Store
    :param lst:
    :return:
    '''
    lst = [i for i in lst if not i.startswith('.')]
    return lst


if __name__ == '__main__':
    shutil.rmtree('processed')
    os.mkdir('processed')

    root_path = 'data'
    # delete auto generated file .DS_Store
    patient_list = deleteAutoGeneratedFile(os.listdir(root_path))

    for patient in patient_list:
        patient_path = os.path.join(root_path, patient)  # e.g. data/9000622



        timestamp_list = sorted(deleteAutoGeneratedFile(os.listdir(patient_path)))
        timestamp_2nd_path = os.path.join(patient_path, timestamp_list[1])  # choose 2nd document e.g. data/9000622/20050707

        record_list = deleteAutoGeneratedFile(os.listdir(timestamp_2nd_path))
        for record in record_list:
            record_path = os.path.join(timestamp_2nd_path, record)  # e.g. data/9000622/20050707/10574201

            dicom_file_list = deleteAutoGeneratedFile(os.listdir(record_path))
            # get realname of one of the dicom file
            dicom_file_series_description = dicomLib.get_dicom_file_series_description(os.path.join(record_path, dicom_file_list[0]))

            # judge whether the dicoms describe SAG_IW_TSE
            if dicom_file_series_description.startswith('SAG_IW_TSE_'):
                # make directory  e.g. processed/9000622/SAG_IW_TSE_LEFT
                dir_path = os.path.join('processed', patient, dicom_file_series_description)
                if not os.path.exists(os.path.join('processed', patient)):
                    os.mkdir(os.path.join('processed', patient))
                if not os.path.exists(os.path.join('processed', patient, dicom_file_series_description)):
                    os.mkdir(dir_path)
                for dicom_file in dicom_file_list:
                    dicom_file_path = os.path.join(record_path, dicom_file)  # e.g. data/9000622/20050707/10574201/001
                    dicomLib.convert_from_dicom_to_jpg(dicom_file_path, os.path.join(dir_path, dicom_file+'.jpeg'))




